<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "appsapp"
 *
 * Auto generated by Extension Builder 2017-12-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Appsapp',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Michael Egli',
    'author_email' => 'michael.egli@appsapp.io',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
